image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
  - port: 6942
    onOpen: ignore

tasks:
  - command: /opt/android-studio/bin/studio.sh
  - command: echo "Hello"


